#!/usr/bin/env python

import argparse as ap
import re
from sys import stdin

p = ap.ArgumentParser(description='Remove prefixes from N-Triples files')

p.add_argument('input', nargs='?', help='Input N-Triples file')

args = p.parse_args()

src = stdin if args.input is None else open(args.input, 'r')

def deprefix(s):
    m0 = re.sub(r"<[^<>]*/([^/]+)>", r"<\1>", s)
    m1 = re.sub(r"[^\s<>\|:\(\)/]*:([^\s<>\|:\(\)/]*)", r"<\1>", m0)
    return m1

#    m1 = re.findall(r":(.*)$", s)
#    if len(m1) > 0:
#        return m1[0]

#    return s

for i in src:
    print(deprefix(i), end='')

src.close()
