#!/usr/bin/env python

import argparse as ap
import re
from sys import stdin

p = ap.ArgumentParser(description='Remove prefixes from N-Triples files')

p.add_argument('input', nargs='?', help='Input N-Triples file')

args = p.parse_args()

src = stdin if args.input is None else open(args.input, 'r')

def deprefix(s):
    m0 = re.findall(r"([^/]+)>$", s)
    if len(m0) > 0:
        return m0[0]

    m1 = re.findall(r":(.*)$", s)
    if len(m1) > 0:
        return m1[0]

    return s

for i in src:
    s = i.strip()
    if len(s) > 0 and s[-1] == '.':
        s = s[:-1].strip()
    s = s.split(maxsplit=3)
    print(' '.join(['<' + deprefix(j) + '>' for j in s]) + ' .')

src.close()
