#!/usr/bin/env python

import re
import os
import argparse as ap

p = ap.ArgumentParser(
    formatter_class=ap.RawDescriptionHelpFormatter,
    description=
"""
Converts NTriples file into a directory with CSV files.

This is primarly used to import the Wikidata in Memgraph and FalkorDB
using its bulk loader (see https://github.com/FalkorDB/falkordb-bulk-loader/).

The script maps each vertex or edge to a number and writes the adjacency matrix
decomposition into the specified directory.

Resulting structure:
- '<output-dir>/<predicate>.csv' is an adjacency matrix for the predicate
- '<output-dir>/Vertex.csv' is a vertices
- '<output-dir>/_vertices.txt' is a vertices
""")
p.add_argument('input', help='Input N-Triples file')
p.add_argument('output', help='Output dir')

args = p.parse_args()

d = args.output
os.mkdir(d)

f =  open(args.input, 'r')
fv = open(f'{d}/Vertex.csv', 'w')
fe = open(f'{d}/_vertices.txt', 'w')

vs = {}
ps = {}
pcs = [0]
gs = [0]

total = 0

i = 0
j = 0
for line in f:
    s = line.split()

    v1 = s[0]
    v1 = v1[v1.find('#')+1:-1] if v1.find('#') != -1 else v1[v1.rfind('/')+1:-1]
    p = s[1]
    p = p[p.find('#')+1:-1] if p.find('#') != -1 else p[p.rfind('/')+1:-1]
    v2 = (" ".join(s[2:]))[:-2]
    v2 = v2[v2.find('#')+1:-1] if v2.find('#') != -1 else v2[v2.rfind('/')+1:-1]

    if v1 not in vs:
        i = i + 1
        vs[v1] = i

    if p not in ps:
        j = j + 1
        ps[p] = j
        gs.append([])
        pcs.append(0)
        with open(f'{d}/{p}.csv', 'w') as g:
            g.write('src,dest\n')
    pcs[ps[p]] += 1

    if v2 not in vs:
        i = i + 1
        vs[v2] = i

    gs[ps[p]].append((v1, v2))

    if len(gs[ps[p]]) > 50000:
        with open(f'{d}/{p}.csv', 'a') as g:
            for l in gs[ps[p]]:
                v1, v2 = l
                g.write(f"{vs[v1]},{vs[v2]}\n")
            gs[ps[p]] = []

    total += 1

fv.write('id\n')
for key in vs:
    fv.write(f'{vs[key]}\n')
    fe.write(f'{key} {vs[key]}\n')

#for key in ps:
#    fe.write(f'{key} {ps[key]}\n')

for p in ps.keys():
    with open(f'{d}/{p}.csv', 'a') as g:
        for l in gs[ps[p]]:
            v1, v2 = l
            g.write(f"{vs[v1]},{vs[v2]}\n")

#for k in range(1, j + 1):
#    with open(f'{d}/{k}.txt', 'r+') as g:
#        content = g.read()
#        g.seek(0, 0)
#        g.write(mm_prelude)
#        g.write(f'{i} {i} {pcs[k]}\n')
#        g.write(content)

print(f"Successfully converteed {args.input}")
print(f"Triples: {total}, vertices: {i}, predicates: {j}")

fv.close()
fe.close()
f.close()
