#!/usr/bin/env python

import argparse as ap
import re
from sys import stdin

p = ap.ArgumentParser(description='Remove duplicates from N-Triples files')

p.add_argument('input', nargs='?', help='Input N-Triples file')

args = p.parse_args()

src = stdin if args.input is None else open(args.input, 'r')

hist = {}
for i in src:
    if i not in hist:
        hist[i] = True
        print(i, end='')

src.close()
