#!/usr/bin/env python

import argparse as ap
import re
from sys import stdin

p = ap.ArgumentParser(description='Truncate RDF N-Triples')

p.add_argument('input', nargs='?', help='Input N-Triples file')
p.add_argument('--s', help='Regex for subject (default: "^<")', default='^<')
p.add_argument('--p', help='Regex for predicate (default: "^<")', default='^<')
p.add_argument('--o', help='Regex for object (default: "^<")', default='^<')

args = p.parse_args()

src = stdin if args.input is None else open(args.input, 'r')

for i in src:
    try:
        s = i.split(maxsplit=3)
        if not re.match(args.s, s[0]) or not re.match(args.o, s[2]) or not re.match(args.p, s[1]):
            continue
        print(i, end='')
    except:
        pass

src.close()
